theme: jekyll-theme-minimal
google_analytics: UA-6780238-15
markdown_ext: "md,txt"
collections:
  D:
    output: true

style: dir
dir_spacification: "-"
dir_links: true
extensions:
  - .pdf
  - .txt
  - .md
truncate: 60
html_link:
  - .md
  - .txt
sections:
  - symbol
  - AAA
  - AA
  - A
  - BBB
  - BB
  - B
  - CCC
  - CC
  - C
